dist: bionic
sudo: required
language: python
python:
- '3.7'
cache:
  - pip
  - apt
addons:
  apt:
    packages:
    - pandoc
    - texlive-latex-base
    - texlive-latex-extra
    - tree
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - texlive-generic-recommended
    - texlive-generic-extra
    - texlive-science
    - texlive-xetex
    - lmodern
    - fonts-cmu
    - inkscape
    - ffmpeg

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  email: rc-softdev@ucl.ac.uk
  keep-history: true
  local-dir: _site
  verbose: true
  on:
    branch: master

install:
- pip install --upgrade setuptools wheel
- pip install -r requirements.txt
- pip install git+https://github.com/ucl-rits/greeter.git
- pip install git+https://github.com/rkern/line_profiler.git
- gem install liquid -v 3.0.6
- gem install jekyll -v 3.1.6
- gem install redcarpet

script:
- python -c "import matplotlib.pyplot"
- ls ch04packaging/*ipynb
- make
before_install:
# Remove the MongoDB repo as their GPG key has expired.
# - sudo rm /etc/apt/sources.list.d/mongodb-3.2.list
- openssl aes-256-cbc -K $encrypted_194007bb00f1_key -iv $encrypted_194007bb00f1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- REPO=`git config remote.origin.url`
- SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
- eval `ssh-agent -s`
- chmod 600 deploy_key
- ssh-add deploy_key
after_success:
